[starts #165807281] Add basic functionality to send activation email
Note(s):
    * Commented out username attribute in member model
        - ran into an error during db downgrade:
        sqlalchemy.exc.CompileError: Can't emit DROP CONSTRAINT
        for constraint ForeignKeyConstraint( ... ); it has no name
        - will attend to this later as I will be introducing more
        attributes to the member model
    * One failing test: test_function_
endpoint_validate_user_token_returns_error_if_member_username_not_found